# BEGIN_KITTY_THEME
include theme.conf
background_opacity 0.6
window_padding_width 12
cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0.5
adjust_line_height 120%
tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground   #141216
active_tab_background   #AC82E9
inactive_tab_foreground #8a7d6e
inactive_tab_background #111014
url_color #AC82E9
url_style curly
inactive_text_alpha 0.1
# END_KITTY_THEME
allow_remote_control yes
dynamic_background_opacity yes